name = "lesson-design-generator"
compatibility_date = "2026-05-22"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "lesson-design-generator-db"
database_id = database_id = "7cf8caed-cd93-4ad6-a525-6452034f631d"

